### ISSUE TITLE
[Component Implementation: Core] ThemeProviderInjector

### ISSUE THREAD

**Issue by ernestoresende** [EightSystems/design-system#45]
### Description
Injects the theme tokens globally making them available to children components.

### Implementation checklist
- [x] The component was tested and is fully working in web environments, without any observable bugs and/or unexpected behavior.
- [x] The component was tested and is fully working in native environments, without any observable bugs and/or unexpected behavior.
- [ ] The component API is fully documented in both the internal Storybook documentation and in-code.

### Implementation notes
None

### Todo
- [ ] Finish documentation on ThemeProviderInjector and custom theme injection with the `useExtendedTheme` hook on both web and native platforms.
- [x] Sync new set of tokens with styles specified on the Penpot design spec.
