### ISSUE TITLE
[Component Implementation: Feedback] Tooltip

### ISSUE THREAD

**Issue by ernestoresende** [EightSystems/design-system#49]
### Description
A brief, informative message that appears when a user interacts with an element (touch on native, click/focus on web).

### Implementation checklist
- [ ] The component was tested and is fully working in web environments, without any observable bugs and/or unexpected behavior.
- [ ] The component was tested and is fully working in native environments, without any observable bugs and/or unexpected behavior.
- [ ] The component API is fully documented in both the internal Storybook documentation and in-code.

### Implementation notes
Current web implementation uses [Popper.js](https://popper.js.org/).

### Todo
- [ ] Further extend props that customize styling.
